# Generated by Django 5.0.1 on 2024-03-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='id',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='username',
            new_name='Full_Name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='username',
        ),
        migrations.AddField(
            model_name='donor',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='Blood_Group',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='Gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipient',
            name='Blood_Group',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipient',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipient',
            name='Full_Name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='Hospital_Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipient',
            name='Hospital_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipient',
            name='Urgency_Level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='donor',
            table='donor_table',
        ),
        migrations.AlterModelTable(
            name='recipient',
            table='recipient_table',
        ),
    ]
